project:
  type: website
  output-dir: .

website:
  title: "pyPLNmodels"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "**Tutorials for count data**"
        contents:
          - index.qmd
          - model_specifying.qmd
          - basic_analysis.qmd
          - zero_inflation.qmd
          - autoreg.qmd
          - clustering.qmd
          - network_analysis.qmd
          - formulas.qmd
      - section: "**Additional Resources**"
        contents:
          - text: "Documentation ğŸ“˜"
            href: https://pln-team.github.io/pyPLNmodels/
            target: _blank
          - text: "GitHub ğŸ™"
            href: https://github.com/PLN-team/pyPLNmodels
            target: _blank
          - text: "PyPI ğŸ“¦"
            href: https://pypi.org/project/pyPLNmodels/
            target: _blank
          - text: "Getting started âŒ¨ï¸ "
            href: https://github.com/PLN-team/pyPLNmodels/blob/main/Getting_started.ipynb
            target: _blank

format:
  html:
    toc: true  # Enables per-page table of contents
    toc-depth: 3
    number-sections: true
    math: true
    css: custom_css_yml.css
    theme: cosme
    code-copy: true
